package net.jamesjennison.filamajignfc.core
import kotlin.test.*

class WriteStateMachineTest {
    private val record=FilamentRecord("p",null,null,FieldValue("B","x"),FieldValue("PLA","x"),FieldValue("P","x"),FieldValue("Red","x"),FieldValue("FF0000","x"),FieldValue("1.75","x"),FieldValue(1000,"x"),null,null,null,null,sourceRevision="r",provenance=Provenance.CUSTOM)
    private val intent=OpenSpoolCodec.encode(record,OpenSpoolProfile.CANONICAL)
    private fun record(payload:ByteArray=intent.payload,mime:String=OpenSpoolCodec.MIME,tnf:Int=2)=TagRecord(tnf,mime,payload)
    private fun tag(uid:ByteArray=byteArrayOf(1),writable:Boolean=true,size:Int=500,records:List<TagRecord> = emptyList())=TagSnapshot(uid,writable,size,records)
    @Test fun emptyReconciliationRemainsUnknownWithoutClaimingCompleteRead() { val sm=WriteStateMachine();sm.restoreUnknown(byteArrayOf(1),intent.payload);sm.reconciled(tag());assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase);assertTrue(sm.state.detail.contains("No NDEF message"));assertFalse(sm.state.detail.contains("does not match")) }
    @Test fun `only fresh matching complete message verifies`() { val sm=WriteStateMachine(); sm.arm(intent); sm.inspected(tag(),300); sm.writeReturned(); sm.reconciled(tag(records=listOf(record()))); assertEquals(WritePhase.VERIFIED,sm.state.phase) }
    @Test fun `canvas raw verification requires exact readback bytes`() { val canvasRecord=record.copy(brand=FieldValue("ELEGOO","x"),nozzleMinC=FieldValue(190,"x"),nozzleMaxC=FieldValue(220,"x"));val intent=ElegooCanvasTagCodec.intent(canvasRecord);val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(size=504),intent.payload.size);sm.writeReturned();sm.reconciled(tag(size=504,records=intent.ndefRecords));assertEquals(WritePhase.VERIFIED,sm.state.phase);val altered=intent.payload.also{it[18]=(it[18].toInt() xor 1).toByte()};val other=WriteStateMachine();other.arm(intent);other.inspected(tag(size=504),intent.payload.size);other.writeReturned();other.reconciled(tag(size=504,records=listOf(TagRecord(-1,ElegooCanvasTagCodec.format.id,altered))));assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,other.state.phase) }
    @Test fun `Creality CFS requires all three exact encrypted blocks before verification`() { val cfs=CrealityCfsTagCodec.intent(record);val sm=WriteStateMachine();sm.arm(cfs);sm.inspected(tag(uid=byteArrayOf(1,2,3,4),size=48),48);sm.writeReturned();val partial=cfs.payload.copyOf().also{it.fill(0,16)};sm.reconciled(tag(uid=byteArrayOf(1,2,3,4),size=48,records=listOf(TagRecord(-1,cfs.codecId,partial))));assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase);val complete=WriteStateMachine();complete.arm(cfs);complete.inspected(tag(uid=byteArrayOf(1,2,3,4),size=48),48);complete.writeReturned();complete.reconciled(tag(uid=byteArrayOf(1,2,3,4),size=48,records=cfs.ndefRecords));assertEquals(WritePhase.VERIFIED,complete.state.phase) }
    @Test fun `successful write with null immediate read requests verification without claiming failure`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag());assertEquals(WritePhase.VERIFICATION_PENDING,sm.state.phase);assertTrue(sm.state.detail.contains("write call completed",ignoreCase=true));sm.reconciled(tag(records=listOf(record())));assertEquals(WritePhase.VERIFIED,sm.state.phase) }
    @Test fun `pending verification ignores a different tag and never rewrites`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag());sm.reconciled(tag(uid=byteArrayOf(2),records=listOf(record())));assertEquals(WritePhase.VERIFICATION_PENDING,sm.state.phase) }
    @Test fun `second tag reuses frozen intent and rejects first tag uid`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag(records=listOf(record())));sm.armSecondTag();assertEquals(2,sm.state.tagNumber);sm.inspected(tag(),300);assertEquals(WritePhase.AWAITING_TAG,sm.state.phase);assertTrue(sm.state.detail.contains("first tag"));sm.inspected(tag(uid=byteArrayOf(2)),300);assertEquals(WritePhase.WRITING,sm.state.phase);assertContentEquals(byteArrayOf(2),sm.state.uid);sm.writeReturned();sm.reconciled(tag(uid=byteArrayOf(2),records=listOf(record())));assertEquals(WritePhase.VERIFIED,sm.state.phase);assertEquals(2,sm.state.tagNumber) }
    @Test fun `verified first tag can finish without a second tag`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag(records=listOf(record())));sm.finishWithOneTag();assertEquals(WritePhase.COMPLETED,sm.state.phase);assertEquals("Completed with one verified tag",sm.state.detail) }
    @Test fun `armed second tag can be cancelled while retaining first completion`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag(records=listOf(record())));sm.armSecondTag();sm.finishWithOneTag();assertEquals(WritePhase.COMPLETED,sm.state.phase) }
    @Test fun `failed second tag can finish with the already verified first tag`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(tag(records=listOf(record())));sm.armSecondTag();sm.inspected(tag(uid=byteArrayOf(2),writable=false),300);assertEquals(WritePhase.REJECTED,sm.state.phase);assertEquals(2,sm.state.tagNumber);sm.finishWithOneTag();assertEquals(WritePhase.COMPLETED,sm.state.phase) }
    @Test fun `pending verification survives restoration and can verify`() { val sm=WriteStateMachine();sm.restorePending(byteArrayOf(1),intent.payload);assertEquals(WritePhase.VERIFICATION_PENDING,sm.state.phase);sm.reconciled(tag(records=listOf(record())));assertEquals(WritePhase.VERIFIED,sm.state.phase) }
    @Test fun `second tag position survives pending restoration`() { val sm=WriteStateMachine();sm.restorePending(byteArrayOf(1),intent.payload,2);assertEquals(2,sm.state.tagNumber);sm.reconciled(tag(records=listOf(record())));assertEquals(WritePhase.VERIFIED,sm.state.phase);assertEquals(2,sm.state.tagNumber) }
    @Test fun `read exception after successful write is pending verification not unknown`() { val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.verificationDeferred("read failed");assertEquals(WritePhase.VERIFICATION_PENDING,sm.state.phase);assertTrue(sm.state.detail.contains("write call completed",ignoreCase=true)) }
    @Test fun `interruption remains unknown and never rewrites`() { val sm=WriteStateMachine(); sm.arm(intent); sm.inspected(tag(),300); sm.writeInterrupted("lost"); assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase); sm.reconciled(tag(records=listOf(record("{}".encodeToByteArray())))); assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase) }
    @Test fun `different uid cannot reconcile`() { val sm=WriteStateMachine(); sm.arm(intent); sm.inspected(tag(),300); sm.writeReturned(); sm.reconciled(tag(byteArrayOf(2),records=listOf(record()))); assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase) }
    @Test fun `existing content consent is bound to uid and content`() { val original=listOf(TagRecord(1,"text/plain",byteArrayOf(1)));val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(records=original),300);assertEquals(WritePhase.NEEDS_OVERWRITE_CONSENT,sm.state.phase);sm.approveOverwrite();sm.inspected(tag(records=listOf(TagRecord(1,"text/plain",byteArrayOf(2)))),300);assertEquals(WritePhase.NEEDS_OVERWRITE_CONSENT,sm.state.phase) }
    @Test fun `approved unchanged content can write`() { val existing=listOf(TagRecord(1,"text/plain",byteArrayOf(1)));val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(records=existing),300);sm.approveOverwrite();sm.inspected(tag(records=existing),300);assertEquals(WritePhase.WRITING,sm.state.phase) }
    @Test fun `extra record wrong tnf or mime cannot verify`() { listOf(tag(records=listOf(record(),TagRecord(1,"text/plain",byteArrayOf(1)))),tag(records=listOf(record(tnf=1))),tag(records=listOf(record(mime="Application/JSON")))).forEach{observed->val sm=WriteStateMachine();sm.arm(intent);sm.inspected(tag(),300);sm.writeReturned();sm.reconciled(observed);assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase)} }
    @Test fun `restored unknown only reconciles matching uid and complete message`() { val sm=WriteStateMachine();sm.restoreUnknown(byteArrayOf(1),intent.payload);sm.reconciled(tag(records=listOf(record())));assertEquals(WritePhase.VERIFIED,sm.state.phase) }
    @Test fun `intent and snapshots defensively copy byte arrays`() { val payload=intent.payload;payload[0]=0;assertTrue(OpenSpoolCodec.semanticallyMatches(intent,intent.payload));val uid=byteArrayOf(1);val snapshot=tag(uid=uid);uid[0]=2;assertContentEquals(byteArrayOf(1),snapshot.uid) }
    @Test fun `read only and undersized reject before write`() { val a=WriteStateMachine(); a.arm(intent); a.inspected(tag(writable=false),300); assertEquals(WritePhase.REJECTED,a.state.phase); val b=WriteStateMachine(); b.arm(intent); b.inspected(tag(size=10),300); assertEquals(WritePhase.REJECTED,b.state.phase) }
    @Test fun unknownReadFailureRemainsUnknownAndCanBeArchived() { val sm=WriteStateMachine();sm.restoreUnknown(byteArrayOf(1),intent.payload);sm.reconciliationReadFailed("Tag lost");assertEquals(WritePhase.WRITE_OUTCOME_UNKNOWN,sm.state.phase);sm.archiveUnknown();assertEquals(WritePhase.UNRESOLVED_ARCHIVED,sm.state.phase);sm.arm(intent);assertEquals(WritePhase.AWAITING_TAG,sm.state.phase) }
}
